function(Setup_Version)
    if (NOT DEFINED PRODUCT_VERSION_MAJOR)
        if (DEFINED ENV{PRODUCT_VERSION_MAJOR})
            set(PRODUCT_VERSION_MAJOR $ENV{PRODUCT_VERSION_MAJOR})
            set(PRODUCT_VERSION_MINOR $ENV{PRODUCT_VERSION_MINOR})
            set(PRODUCT_VERSION_PATCH $ENV{PRODUCT_VERSION_PATCH})
            set(PRODUCT_VERSION_BUILD $ENV{PRODUCT_VERSION_BUILD})
            message("use env product version ${PRODUCT_VERSION_MAJOR}.${PRODUCT_VERSION_MINOR}.${PRODUCT_VERSION_PATCH}.${PRODUCT_VERSION_BUILD}")
        else()
            set(PRODUCT_VERSION_MAJOR 1)
            set(PRODUCT_VERSION_MINOR 0)
            set(PRODUCT_VERSION_PATCH 0)
            set(PRODUCT_VERSION_BUILD 0)
            message("set default product version ${PRODUCT_VERSION_MAJOR}.${PRODUCT_VERSION_MINOR}.${PRODUCT_VERSION_PATCH}.${PRODUCT_VERSION_BUILD} ")
        endif()
    else()
        message("use defined product version: ${PRODUCT_VERSION_MAJOR}.${PRODUCT_VERSION_MINOR}.${PRODUCT_VERSION_PATCH}.${PRODUCT_VERSION_BUILD} ")
    endif()
    message("STEUP_VERSION is called")

    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Version.rc.in ${CMAKE_CURRENT_BINARY_DIR}/Version.rc)
endfunction()
